version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: usr_agenda
      POSTGRES_PASSWORD: D@ck&r@2025
      POSTGRES_DB: db_agenda
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_backend
    restart: always
    environment:
      DATABASE_URL: postgres://usr_agenda:D@ck&r@2025@postgres:5432/db_agenda
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
